const VF_PRODUCTS={check:{id:'check',name:'Travel Check',price:29,short:'Scopri esattamente cosa ti serve per partire.',description:'Analisi personalizzata di passaporto, destinazione, durata, scali e principali requisiti del viaggio.',features:['Checklist personalizzata','Passaporto e validità residua','Visti, ETA, eVisa e moduli','Scali e transiti','Biglietto di uscita','Indicazioni sui documenti da portare']},assist:{id:'assist',name:'Travel Check + Assistenza',price:69,short:'Fai tu le pratiche, ma con una persona che ti segue.',description:'Tutto il Travel Check, più assistenza durante la preparazione e controllo dei documenti prima dell’invio.',features:['Tutto il Travel Check','Supporto umano','Controllo documenti','Assistenza su moduli e pratiche','Verifica finale prima della partenza']},done:{id:'done',name:'Facciamo Noi',price:99,short:'Delega a noi le pratiche semplici che possono essere gestite per tuo conto.',description:'Analizziamo il viaggio, raccogliamo i documenti e gestiamo le pratiche delegabili previste dal servizio.',features:['Analisi completa','Raccolta documenti','Gestione pratiche delegabili','Controllo finale','Referente umano']},complex:{id:'complex',name:'Viaggio Complesso',price:149,short:'Per più Paesi, soggiorni lunghi, business, studio o itinerari particolari.',description:'Analisi avanzata per itinerari e casi che richiedono verifiche multiple o una valutazione dedicata.',features:['Più Paesi e scali','Business / studio / remote work','Soggiorni lunghi','Requisiti speciali','Valutazione umana dedicata']}};
const VF_CART_KEY='vf_cart',VF_ORDERS_KEY='vf_orders';
function vfMoney(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function vfGetCart(){try{return JSON.parse(localStorage.getItem(VF_CART_KEY)||'[]')}catch{return[]}}
function vfSaveCart(c){localStorage.setItem(VF_CART_KEY,JSON.stringify(c));vfUpdateCartBadges()}
function vfAddToCart(id,qty=1){if(!VF_PRODUCTS[id])return;const c=vfGetCart(),i=c.findIndex(x=>x.id===id);if(i>=0)c[i].qty+=qty;else c.push({id,qty});vfSaveCart(c);return c}
function vfRemoveFromCart(id){vfSaveCart(vfGetCart().filter(x=>x.id!==id))}
function vfSetQty(id,qty){const c=vfGetCart();const i=c.findIndex(x=>x.id===id);if(i<0)return;if(qty<=0)c.splice(i,1);else c[i].qty=qty;vfSaveCart(c)}
function vfCartCount(){return vfGetCart().reduce((s,x)=>s+x.qty,0)}
function vfCartTotal(){return vfGetCart().reduce((s,x)=>s+(VF_PRODUCTS[x.id]?.price||0)*x.qty,0)}
function vfUpdateCartBadges(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=vfCartCount())}
function vfBuyNow(id){vfSaveCart([{id,qty:1}]);location.href='checkout.html'}
function vfGetOrders(){try{return JSON.parse(localStorage.getItem(VF_ORDERS_KEY)||'[]')}catch{return[]}}
function vfSaveOrders(o){localStorage.setItem(VF_ORDERS_KEY,JSON.stringify(o))}
function vfCreateOrder(customer,payment='Da pagare'){const cart=vfGetCart();if(!cart.length)return null;const now=new Date();const order={id:'VF-'+now.getFullYear()+'-'+String(Date.now()).slice(-7),created:now.toISOString(),customer,items:cart.map(x=>({...x,name:VF_PRODUCTS[x.id].name,price:VF_PRODUCTS[x.id].price})),total:vfCartTotal(),payment,status:'Ordine ricevuto',progress:20,steps:[{name:'Ordine ricevuto',done:true},{name:'Dati del viaggio',done:false},{name:'Documenti caricati',done:false},{name:'Verifica VistoFacile',done:false},{name:'Pratica completata',done:false}]};const orders=vfGetOrders();orders.unshift(order);vfSaveOrders(orders);const leads=(()=>{try{return JSON.parse(localStorage.getItem('vf_leads')||'[]')}catch{return[]}})();leads.unshift({id:order.id,nome:[customer.nome,customer.cognome].filter(Boolean).join(' '),email:customer.email||'',telefono:customer.telefono||'',creato:order.created,stato:'Nuovo',servizio:order.items.map(i=>i.name).join(' + '),valore:order.total,pagamento:payment,responsabile:'',todo:['Verificare ordine','Richiedere/completare dati viaggio','Controllare documenti','Avviare pratica'],call:[],scadenze:[],origine:'E-commerce'});localStorage.setItem('vf_leads',JSON.stringify(leads));localStorage.setItem('vf_active_order',order.id);vfSaveCart([]);return order}
function vfGetOrder(id){return vfGetOrders().find(o=>o.id===id)}
function vfUpdateOrder(order){const list=vfGetOrders(),i=list.findIndex(o=>o.id===order.id);if(i>=0){list[i]=order;vfSaveOrders(list)}}
function vfAddLeadGenLinks(){if(!document.querySelector('.hero'))return;const nav=document.querySelector('.links');if(nav&&!nav.querySelector('[data-free-profile]')){const a=document.createElement('a');a.href='registrazione.html';a.textContent='Profilo gratis';a.setAttribute('data-free-profile','1');const cart=nav.querySelector('.cart');nav.insertBefore(a,cart||null)}const actions=document.querySelector('.hero .actions');if(actions&&!actions.querySelector('[data-free-profile]')){const a=document.createElement('a');a.href='registrazione.html';a.className='btn ghost';a.textContent='Crea profilo gratis';a.setAttribute('data-free-profile','1');actions.appendChild(a)}}
function vfFixDestinationChips(){document.querySelectorAll('#worldwide .docmini').forEach(box=>{const labels=[...box.querySelectorAll('span')].map(s=>s.textContent.trim()).filter(Boolean).filter(t=>!/^passaporto$/i.test(t));box.innerHTML='';labels.slice(0,2).forEach(t=>{const s=document.createElement('span');s.textContent=t;box.appendChild(s)});const a=document.createElement('a');a.href='#servizi';a.textContent='Elenco completo';a.style.cssText='font-size:10px;line-height:1.15;font-weight:850;padding:6px 8px;border-radius:999px;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.22);backdrop-filter:blur(6px);color:#fff;text-decoration:none';box.appendChild(a)})}
function vfAddUnsureSection(){const servizi=document.getElementById('servizi');if(!servizi||document.getElementById('vf-unsure'))return;const section=document.createElement('section');section.id='vf-unsure';section.className='section dark';section.innerHTML=`<div class="wrap"><div class="kicker">Non sai cosa scegliere?</div><h2>Raccontaci il tuo viaggio. Ti aiutiamo a capire quale pacchetto fa per te.</h2><p class="intro">Compila il modulo con destinazione, date, scali e tipo di viaggio. Ti invieremo una mini guida iniziale con le cose da controllare e il servizio più adatto al tuo caso.</p><div class="actions"><a class="btn light" href="richiesta.html">Parlaci del tuo viaggio</a><a class="btn ghost" href="registrazione.html">Crea il profilo gratis</a></div></div>`;servizi.insertAdjacentElement('afterend',section)}
document.addEventListener('DOMContentLoaded',()=>{vfUpdateCartBadges();vfAddLeadGenLinks();vfFixDestinationChips();vfAddUnsureSection()});