const VF_PRODUCTS={check:{id:'check',name:'Travel Check',price:29,short:'Scopri esattamente cosa ti serve per partire.',description:'Analisi personalizzata di passaporto, destinazione, durata, scali e principali requisiti del viaggio.',features:['Checklist personalizzata','Passaporto e validità residua','Visti, ETA, eVisa e moduli','Scali e transiti','Biglietto di uscita','Indicazioni sui documenti da portare']},assist:{id:'assist',name:'Travel Check + Assistenza',price:69,short:'Fai tu le pratiche, ma con una persona che ti segue.',description:'Tutto il Travel Check, più assistenza durante la preparazione e controllo dei documenti prima dell’invio.',features:['Tutto il Travel Check','Supporto umano','Controllo documenti','Assistenza su moduli e pratiche','Verifica finale prima della partenza']},done:{id:'done',name:'Facciamo Noi',price:99,short:'Delega a noi le pratiche semplici che possono essere gestite per tuo conto.',description:'Analizziamo il viaggio, raccogliamo i documenti e gestiamo le pratiche delegabili previste dal servizio.',features:['Analisi completa','Raccolta documenti','Gestione pratiche delegabili','Controllo finale','Referente umano']},complex:{id:'complex',name:'Viaggio Complesso',price:149,short:'Per più Paesi, soggiorni lunghi, business, studio o itinerari particolari.',description:'Analisi avanzata per itinerari e casi che richiedono verifiche multiple o una valutazione dedicata.',features:['Più Paesi e scali','Business / studio / remote work','Soggiorni lunghi','Requisiti speciali','Valutazione umana dedicata']}};
const VF_CART_KEY='vf_cart',VF_ORDERS_KEY='vf_orders';
function vfMoney(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function vfGetCart(){try{return JSON.parse(localStorage.getItem(VF_CART_KEY)||'[]')}catch{return[]}}
function vfSaveCart(c){localStorage.setItem(VF_CART_KEY,JSON.stringify(c));vfUpdateCartBadges()}
function vfAddToCart(id,qty=1){if(!VF_PRODUCTS[id])return;const c=vfGetCart(),i=c.findIndex(x=>x.id===id);if(i>=0)c[i].qty+=qty;else c.push({id,qty});vfSaveCart(c);return c}
function vfRemoveFromCart(id){vfSaveCart(vfGetCart().filter(x=>x.id!==id))}
function vfSetQty(id,qty){const c=vfGetCart();const i=c.findIndex(x=>x.id===id);if(i<0)return;if(qty<=0)c.splice(i,1);else c[i].qty=qty;vfSaveCart(c)}
function vfCartCount(){return vfGetCart().reduce((s,x)=>s+x.qty,0)}
function vfCartTotal(){return vfGetCart().reduce((s,x)=>s+(VF_PRODUCTS[x.id]?.price||0)*x.qty,0)}
function vfUpdateCartBadges(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=vfCartCount())}
function vfBuyNow(id){vfSaveCart([{id,qty:1}]);location.href='checkout.html'}
function vfGetOrders(){try{return JSON.parse(localStorage.getItem(VF_ORDERS_KEY)||'[]')}catch{return[]}}
function vfSaveOrders(o){localStorage.setItem(VF_ORDERS_KEY,JSON.stringify(o))}
function vfCreateOrder(customer,payment='Da pagare'){const cart=vfGetCart();if(!cart.length)return null;const now=new Date();const order={id:'VF-'+now.getFullYear()+'-'+String(Date.now()).slice(-7),created:now.toISOString(),customer,items:cart.map(x=>({...x,name:VF_PRODUCTS[x.id].name,price:VF_PRODUCTS[x.id].price})),total:vfCartTotal(),payment,status:'Ordine ricevuto',progress:20,steps:[{name:'Ordine ricevuto',done:true},{name:'Dati del viaggio',done:false},{name:'Documenti caricati',done:false},{name:'Verifica VistoFacile',done:false},{name:'Pratica completata',done:false}]};const orders=vfGetOrders();orders.unshift(order);vfSaveOrders(orders);const leads=(()=>{try{return JSON.parse(localStorage.getItem('vf_leads')||'[]')}catch{return[]}})();leads.unshift({id:order.id,nome:[customer.nome,customer.cognome].filter(Boolean).join(' '),email:customer.email||'',telefono:customer.telefono||'',creato:order.created,stato:'Nuovo',servizio:order.items.map(i=>i.name).join(' + '),valore:order.total,pagamento:payment,responsabile:'',todo:['Verificare ordine','Richiedere/completare dati viaggio','Controllare documenti','Avviare pratica'],call:[],scadenze:[],origine:'E-commerce'});localStorage.setItem('vf_leads',JSON.stringify(leads));localStorage.setItem('vf_active_order',order.id);vfSaveCart([]);return order}
function vfGetOrder(id){return vfGetOrders().find(o=>o.id===id)}
function vfUpdateOrder(order){const list=vfGetOrders(),i=list.findIndex(o=>o.id===order.id);if(i>=0){list[i]=order;vfSaveOrders(list)}}
function vfAddLeadGenLinks(){if(!document.querySelector('.hero'))return;const nav=document.querySelector('.links');if(nav&&!nav.querySelector('[data-free-profile]')){const a=document.createElement('a');a.href='registrazione.html';a.textContent='Profilo gratis';a.setAttribute('data-free-profile','1');const cart=nav.querySelector('.cart');nav.insertBefore(a,cart||null)}const actions=document.querySelector('.hero .actions');if(actions&&!actions.querySelector('[data-free-profile]')){const a=document.createElement('a');a.href='registrazione.html';a.className='btn ghost';a.textContent='Crea profilo gratis';a.setAttribute('data-free-profile','1');actions.appendChild(a)}}
function vfFixDestinationChips(){document.querySelectorAll('#worldwide .docmini').forEach(box=>{const labels=[...box.querySelectorAll('span,a')].map(s=>s.textContent.trim()).filter(Boolean).filter(t=>!/passaporto/i.test(t)&&!/elenco completo/i.test(t)&&!/tutti i documenti/i.test(t));box.innerHTML='';labels.slice(0,2).forEach(t=>{const s=document.createElement('span');s.textContent=t;box.appendChild(s)});const a=document.createElement('a');a.href='#servizi';a.textContent='Tutti i documenti';a.style.cssText='font-size:10px;line-height:1.15;font-weight:850;padding:6px 8px;border-radius:999px;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.22);backdrop-filter:blur(6px);color:#fff;text-decoration:none';box.appendChild(a)})}
function vfInjectExperienceStyles(){if(document.getElementById('vfExperienceStyles'))return;const s=document.createElement('style');s.id='vfExperienceStyles';s.textContent=`
#vf-unsure{background:#f5f3ee!important;color:#111!important;padding:58px 0 28px!important}
.vf-choice-shell{position:relative;min-height:610px;border-radius:34px;overflow:hidden;background:#111;display:grid;grid-template-columns:1.05fr .95fr;box-shadow:0 24px 70px rgba(0,0,0,.13)}
.vf-choice-photo{position:relative;min-height:610px;background:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.58)),url('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=92') center/cover}
.vf-choice-photo:after{content:'Dove vuoi andare?';position:absolute;left:34px;bottom:30px;color:#fff;font-size:34px;line-height:1;font-weight:950;letter-spacing:-.045em}
.vf-choice-content{padding:56px 52px;color:#fff;display:flex;flex-direction:column;justify-content:center}
.vf-choice-content .kicker{color:#aaa}
.vf-choice-content h2{font-size:50px;line-height:.98;letter-spacing:-.055em;margin:12px 0 16px;max-width:620px}
.vf-choice-content>p{font-size:17px;line-height:1.55;color:#bbb;max-width:610px;margin:0}
.vf-choice-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:30px 0 4px}
.vf-choice-step{padding:16px 15px;border:1px solid #303030;border-radius:17px;background:rgba(255,255,255,.045)}
.vf-choice-step b{display:block;font-size:12px;margin-bottom:5px}.vf-choice-step span{font-size:11px;color:#aaa;line-height:1.35;display:block}
.vf-choice-content .actions{margin-top:24px}.vf-choice-content .btn.light{background:#fff;color:#111;border-color:#fff}.vf-choice-content .btn.ghost{color:#fff;border-color:#555}
.vf-mini-guide{position:absolute;left:28px;top:28px;background:rgba(255,255,255,.92);backdrop-filter:blur(14px);border-radius:20px;padding:18px 19px;color:#111;max-width:250px;box-shadow:0 15px 35px rgba(0,0,0,.18)}
.vf-mini-guide small{font-size:9px;text-transform:uppercase;letter-spacing:.13em;font-weight:950;color:#777}.vf-mini-guide strong{display:block;font-size:18px;line-height:1.08;margin:6px 0 8px}.vf-mini-guide span{font-size:11px;color:#666;line-height:1.35;display:block}
.vf-check-section{background:#fff!important;color:#111!important;padding:72px 0 92px!important}
.vf-check-layout{display:grid;grid-template-columns:.72fr 1.28fr;gap:46px;align-items:start}
.vf-check-copy{position:sticky;top:110px}.vf-check-copy h2{font-size:50px!important}.vf-check-copy .intro{color:#6b6862!important}.vf-check-copy .btn{background:#111!important;color:#fff!important;border-color:#111!important}
.vf-check-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.vf-check-card{border:1px solid #e5e0d7;border-radius:20px;padding:20px;background:#faf9f6;min-height:126px;transition:.25s}.vf-check-card:hover{transform:translateY(-3px);box-shadow:0 14px 30px rgba(0,0,0,.06);background:#fff}
.vf-check-icon{width:34px;height:34px;border-radius:50%;background:#111;color:#fff;display:grid;place-items:center;font-size:15px;margin-bottom:13px}.vf-check-card b{display:block;font-size:16px;margin-bottom:5px}.vf-check-card span{display:block;color:#777;font-size:12px;line-height:1.4}
@media(max-width:900px){.vf-choice-shell,.vf-check-layout{grid-template-columns:1fr}.vf-choice-photo{min-height:390px}.vf-choice-content{padding:38px 28px}.vf-choice-content h2{font-size:40px}.vf-check-copy{position:static}.vf-choice-steps{grid-template-columns:1fr 1fr 1fr}}
@media(max-width:620px){.vf-choice-shell{border-radius:26px}.vf-choice-photo{min-height:330px}.vf-mini-guide{left:18px;top:18px;max-width:215px}.vf-choice-content h2{font-size:36px}.vf-choice-steps,.vf-check-grid{grid-template-columns:1fr}.vf-choice-content{padding:32px 22px}.vf-check-copy h2{font-size:39px!important}}
`;document.head.appendChild(s)}
function vfAddUnsureSection(){const servizi=document.getElementById('servizi');if(!servizi||document.getElementById('vf-unsure'))return;const section=document.createElement('section');section.id='vf-unsure';section.className='section';section.innerHTML=`<div class="wrap"><div class="vf-choice-shell"><div class="vf-choice-photo"><div class="vf-mini-guide"><small>Mini guida gratuita</small><strong>Prima capiamo il viaggio.</strong><span>Destinazione, date, scali e tipo di esperienza. Poi ti diciamo cosa controllare e quale servizio ha senso per te.</span></div></div><div class="vf-choice-content"><div class="kicker">Non sai cosa scegliere?</div><h2>Raccontaci dove vuoi andare. Al resto pensiamo insieme.</h2><p>Non devi capire da solo quale pacchetto acquistare. Raccontaci il viaggio e ricevi una prima lettura del caso con i punti da controllare.</p><div class="vf-choice-steps"><div class="vf-choice-step"><b>01 · Racconta</b><span>Destinazione, date, scali e motivo.</span></div><div class="vf-choice-step"><b>02 · Ricevi</b><span>Mini guida iniziale sul tuo viaggio.</span></div><div class="vf-choice-step"><b>03 · Scegli</b><span>Il servizio più adatto, senza comprare alla cieca.</span></div></div><div class="actions"><a class="btn light" href="richiesta.html">Parlaci del tuo viaggio</a><a class="btn ghost" href="registrazione.html">Crea il profilo gratis</a></div></div></div></div>`;servizi.insertAdjacentElement('afterend',section)}
function vfUpgradeChecklistSection(){const sections=[...document.querySelectorAll('section.dark')];const target=sections.find(sec=>sec.querySelector('.kicker')?.textContent.trim().toLowerCase()==='cosa controlliamo');if(!target||target.dataset.vfUpgraded)return;target.dataset.vfUpgraded='1';target.classList.remove('dark');target.classList.add('vf-check-section');const wrap=target.querySelector('.wrap');if(!wrap)return;wrap.innerHTML=`<div class="vf-check-layout"><div class="vf-check-copy"><div class="kicker">Cosa controlliamo</div><h2>Il visto è solo una riga della checklist.</h2><p class="intro">Il punto non è avere “dei documenti”. È avere quelli giusti, nel formato giusto, per il tuo itinerario reale.</p><div class="actions"><a class="btn" href="richiesta.html">Controlla tutto per me</a></div></div><div class="vf-check-grid"><div class="vf-check-card"><div class="vf-check-icon">✓</div><b>Ingresso</b><span>Visti, ETA, eVisa, esenzioni e moduli di arrivo.</span></div><div class="vf-check-card"><div class="vf-check-icon">↗</div><b>Scali e transiti</b><span>Self-transfer, ritiro bagagli, cambio aeroporto e visti di transito.</span></div><div class="vf-check-card"><div class="vf-check-icon">↩</div><b>Uscita dal Paese</b><span>Onward ticket, ritorno, permanenza massima ed eventuali estensioni.</span></div><div class="vf-check-card"><div class="vf-check-icon">€</div><b>Prove economiche</b><span>Fondi, prenotazioni, assicurazioni e documenti richiesti alla frontiera.</span></div><div class="vf-check-card"><div class="vf-check-icon">+</div><b>Salute e assicurazione</b><span>Requisiti sanitari, certificati, farmaci e coperture obbligatorie.</span></div><div class="vf-check-card"><div class="vf-check-icon">⌁</div><b>Casi particolari</b><span>Minori, patente internazionale, business, studio e soggiorni lunghi.</span></div></div></div>`}
document.addEventListener('DOMContentLoaded',()=>{vfUpdateCartBadges();vfInjectExperienceStyles();vfAddLeadGenLinks();vfFixDestinationChips();vfAddUnsureSection();vfUpgradeChecklistSection()});